# Generated by Django 4.1.1 on 2022-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuarios',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
